"""Initial migration

Revision ID: e644bdb0b2f5
Revises: 
Create Date: 2026-09-14 00:14:49.829819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e644bdb0b2f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_message_timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_preview', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(length=100), nullable=True),
    sa.Column('strategy_params_json', sa.Text(), nullable=True),
    sa.Column('chat_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('chat_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('tech_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('tech_completion_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    # ### end Alembic commands ###
