"""Initial migration

Revision ID: f2f64ebfe7dc
Revises: 
Create Date: 2026-09-20 20:41:21.646561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f64ebfe7dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_message_timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_preview', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('is_dialog_remembered', sa.Boolean(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(length=100), nullable=True),
    sa.Column('strategy_params_json', sa.Text(), nullable=True),
    sa.Column('chat_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('chat_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('tech_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('tech_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('task_profile_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['task_profile_id'], ['task_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    op.drop_table('task_profiles')
    # ### end Alembic commands ###
